export const SOCKET_EVENT = {
  HOST_JOIN_ROOM: 'host_join_room',
  PLAYER_JOIN_ROOM: 'player_join_room',
  PLAYER_JOINED_ROOM: 'player_joined_room',
  START_GAME: 'start_game',
  NEW_QUESTION: 'new_question',
  PLAYER_GET_QUESTION: 'player_get_question',
  HOST_GET_QUESTION: 'host_get_question',
  TIMER_UDPATE: 'timer_update',
  QUESTION_TIME_UP: 'question_time_up',
  END_QUESTION_EARLY: 'end_question_early',
  PLAYER_SUBMIT_ANSWER: 'player_submit_answer',
  GET_LEADERBOARD: 'get_leaderboard',
  HOST_CURRENT_LEADERBOARD: 'host_current_leaderboard',
  PLAYER_CURRENT_LEADERBOARD: 'player_current_leaderboard',
  GET_PLAYER_RESULT: 'get_player_result',
  PLAYER_RESULT: 'player_result',
  HOST_FINISH_GAME: 'host_finish_game',
  FINISH_GAME: 'finish_game',
  HOST_FINAL_LEADERBOARD: 'host_final_leaderboard',
  PLAYER_FINAL_LEADERBOARD: 'player_final_leaderboard',
};

export const SOCKET_EVENT_ERROR = {
  HOST_JOIN_ROOM_ERROR: 'host_join_room_error',
  PLAYER_JOIN_ROOM_ERROR: 'player_join_room_error',
  HOST_START_GAME_ERROR: 'host_start_game_error',
  NEW_QUESTION_ERROR: 'new_question_error',
  QUESTION_TIME_UP_ERROR: 'question_time_up_error',
  PLAYER_SUBMIT_ANSWER_ERROR: 'player_submit_answer_error',
  GET_LEADERBOARD_ERROR: 'get_leaderboard_error',
  GET_PLAYER_RESULT_ERROR: 'get_player_result_error',
  FINISH_GAME_ERROR: 'finish_game_error',
};
